name: provisional-data

on:
  push:
    branches: main
  schedule:
    - cron: "30 */4 * * *"

jobs:
  provis-data:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    steps:
      - name: checkout repo    
        uses: actions/checkout@v3
        
      - name: checkout fedsdata
        uses: actions/checkout@v3
        with:
          repository: USEPA/fedsdata
          path: fedsdata
          token: ${{ secrets.MY_TOKEN }}  

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'release'

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('stringr', 'arrow', 'lubridate'))"
          Rscript -e "install.packages(c('dplyr', 'readr', 'tidyr', 'purrr'))"
          
      - name: merge data
        run: |
          Rscript -e "source('R/merge_buoy_data.R')"
      
      - name: create provisional data files
        run: |
          Rscript -e "source('R/provisional_data.R')"
          
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add "data/merged_buoy_data.feather"
          git commit -am "add merged buoy data"
          git push 